/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DeploymentInfo, PluginManagerSnapshot, ProfilePluginSnapshot, RemovePluginRequest, RemovePluginResult } from '@deepseek-ai/dsh-host-plugin-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e4d616e61676572 {
    deployment: () => Promise<RemoteResult<DeploymentInfo>>
    list: () => Promise<RemoteResult<PluginManagerSnapshot>>
    profileList: () => Promise<RemoteResult<ProfilePluginSnapshot>>
    removePlugin: (request: RemovePluginRequest) => Promise<RemoteResult<RemovePluginResult>>
  }
  interface TypertRemoteMap {
    'pluginManager/deployment': () => Promise<RemoteResult<DeploymentInfo>>
    'pluginManager/list': () => Promise<RemoteResult<PluginManagerSnapshot>>
    'pluginManager/profileList': () => Promise<RemoteResult<ProfilePluginSnapshot>>
    'pluginManager/removePlugin': (request: RemovePluginRequest) => Promise<RemoteResult<RemovePluginResult>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginManager': TypertRemoteNamespace$706c7567696e4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
