/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_host_plugin_manager_pluginManager_deployment_result$schema = z.object({
  'flavor': z.union([z.literal("test"), z.literal("exe")]).readonly(),
})
const _deepseek_ai_dsh_host_plugin_manager_pluginManager_list_result$schema = z.object({
  'plugins': z.array(z.object({
  'pluginName': z.string().readonly(),
  'displayName': z.string().readonly(),
  'mainDir': z.union([z.literal(null), z.string()]).readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
})).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_host_plugin_manager_pluginManager_profileList_result$schema = z.object({
  'profile': z.string().readonly(),
  'plugins': z.array(z.object({
  'packageName': z.string().readonly(),
  'displayName': z.string().readonly(),
  'description': z.string().readonly(),
  'spec': z.string().readonly(),
  'dependencies': z.array(z.object({
  'name': z.string().readonly(),
  'spec': z.string().readonly(),
})).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_host_plugin_manager_pluginManager_removePlugin_parameter_0$schema = z.object({
  'pluginName': z.string().readonly(),
})
const _deepseek_ai_dsh_host_plugin_manager_pluginManager_removePlugin_result$schema = z.object({
  'removed': z.boolean().readonly(),
  'message': z.string().readonly().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-host-plugin-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-host-plugin-manager#pluginManager/deployment',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'deployment',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-plugin-manager/types#DeploymentInfo',
        schema: _deepseek_ai_dsh_host_plugin_manager_pluginManager_deployment_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-manager/src/index.ts","line":78,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-host-plugin-manager#pluginManager/list',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-plugin-manager/types#PluginManagerSnapshot',
        schema: _deepseek_ai_dsh_host_plugin_manager_pluginManager_list_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-manager/src/index.ts","line":87,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-host-plugin-manager#pluginManager/profileList',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'profileList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-plugin-manager/types#ProfilePluginSnapshot',
        schema: _deepseek_ai_dsh_host_plugin_manager_pluginManager_profileList_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-manager/src/index.ts","line":115,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-host-plugin-manager#pluginManager/removePlugin',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'removePlugin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-plugin-manager/types#RemovePluginRequest',
            schema: _deepseek_ai_dsh_host_plugin_manager_pluginManager_removePlugin_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-plugin-manager/types#RemovePluginResult',
        schema: _deepseek_ai_dsh_host_plugin_manager_pluginManager_removePlugin_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-manager/src/index.ts","line":148,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
